"""Catalog of compliance frameworks ingested into the database.

Each entry maps a canonical framework_id to:
- Display name and version
- Tier (1=universal, 2=common, 3=sectoral)
- Source format and file path
- Parent framework (for implementing acts, sub-frameworks)
- Issuing body

This is the authoritative list of frameworks the database stores.
"""
from __future__ import annotations

# Framework catalog: id -> metadata
FRAMEWORK_CATALOG: list[dict] = [
    # ────── Tier 1: Universal (every EU AI software company) ──────
    {
        "id": "32024R1689",  # use CELEX for EU laws
        "category": "eu_law",
        "name": "EU AI Act",
        "version": "Reg. (EU) 2024/1689",
        "issuing_body": "European Parliament and Council",
        "tier": 1,
        "source_format": "html",
        "source_file": "32024R1689.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1689",
        "license": "Public domain (EU legislation)",
        "description": "Horizontal AI regulation. Risk-tiered obligations for AI system providers, deployers, importers, distributors.",
    },
    {
        "id": "32016R0679",
        "category": "eu_law",
        "name": "GDPR",
        "version": "Reg. (EU) 2016/679",
        "issuing_body": "European Parliament and Council",
        "tier": 1,
        "source_format": "html",
        "source_file": "32016R0679.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679",
        "license": "Public domain (EU legislation)",
        "description": "Personal data processing regulation. Applies to any AI company processing personal data.",
    },
    {
        "id": "32024R2847",
        "category": "eu_law",
        "name": "Cyber Resilience Act (CRA)",
        "version": "Reg. (EU) 2024/2847",
        "issuing_body": "European Parliament and Council",
        "tier": 1,
        "source_format": "html",
        "source_file": "32024R2847.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R2847",
        "license": "Public domain (EU legislation)",
        "description": "Cybersecurity obligations for products with digital elements. Applies to any software placed on EU market.",
    },
    {
        "id": "32025R2392",
        "category": "eu_law",
        "name": "CRA Implementing Reg — Categories of important/critical products",
        "version": "Reg. (EU) 2025/2392",
        "issuing_body": "European Commission",
        "tier": 1,
        "parent_id": "32024R2847",
        "source_format": "html",
        "source_file": "32025R2392.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32025R2392",
        "license": "Public domain",
        "description": "Technical description of categories of important and critical products with digital elements under CRA.",
    },
    {
        "id": "32026R0881",
        "category": "eu_law",
        "name": "CRA Delegated Reg — Conformity assessment procedures",
        "version": "Reg. (EU) 2026/881",
        "issuing_body": "European Commission",
        "tier": 1,
        "parent_id": "32024R2847",
        "source_format": "html",
        "source_file": "32026R0881.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32026R0881",
        "license": "Public domain",
        "description": "Specifies terms and conditions for applying conformity assessment procedures under CRA.",
    },
    {
        "id": "32025R1535",
        "category": "eu_law",
        "name": "CRA Delegated Reg — Exclusions",
        "version": "Reg. (EU) 2025/1535",
        "issuing_body": "European Commission",
        "tier": 1,
        "parent_id": "32024R2847",
        "source_format": "html",
        "source_file": "32025R1535.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32025R1535",
        "license": "Public domain",
        "description": "Defines exclusions from CRA application (products covered by other Union law).",
    },

    # ────── Tier 2: Common (most EU AI companies) ──────
    {
        "id": "32022L2555",
        "category": "eu_law",
        "name": "NIS2 Directive",
        "version": "Dir. (EU) 2022/2555",
        "issuing_body": "European Parliament and Council",
        "tier": 2,
        "source_format": "html",
        "source_file": "32022L2555.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2555",
        "license": "Public domain",
        "description": "Cybersecurity of essential and important entities. Many B2B SaaS qualify.",
    },
    {
        "id": "32024L2853",
        "category": "eu_law",
        "name": "Product Liability Directive",
        "version": "Dir. (EU) 2024/2853",
        "issuing_body": "European Parliament and Council",
        "tier": 2,
        "source_format": "html",
        "source_file": "32024L2853.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024L2853",
        "license": "Public domain",
        "description": "Updated product liability rules explicitly covering AI products and software defects.",
    },
    {
        "id": "32023R2854",
        "category": "eu_law",
        "name": "Data Act",
        "version": "Reg. (EU) 2023/2854",
        "issuing_body": "European Parliament and Council",
        "tier": 2,
        "source_format": "html",
        "source_file": "32023R2854.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32023R2854",
        "license": "Public domain",
        "description": "IoT data access/sharing, cloud switching, B2B data sharing.",
    },
    {
        "id": "32026R1744",
        "category": "eu_law",
        "name": "Digital Omnibus on AI",
        "version": "Reg. (EU) 2026/1744",
        "issuing_body": "European Parliament and Council",
        "tier": 2,
        "parent_id": "32024R1689",
        "source_format": "html",
        "source_file": "32026R1744.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32026R1744",
        "license": "Public domain",
        "description": "Amends AI Act and aviation/machinery regulations. Simplifies AI Act implementation.",
    },
    {
        "id": "32025R0454",
        "category": "eu_law",
        "name": "AI Act Scientific Panel Reg",
        "version": "Reg. (EU) 2025/454",
        "issuing_body": "European Commission",
        "tier": 2,
        "parent_id": "32024R1689",
        "source_format": "html",
        "source_file": "32025R0454.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32025R0454",
        "license": "Public domain",
        "description": "Establishes the AI Act's scientific panel of independent experts.",
    },
    {
        "id": "32026R1755",
        "category": "eu_law",
        "name": "AI Act Commission Proceedings Reg",
        "version": "Reg. (EU) 2026/1755",
        "issuing_body": "European Commission",
        "tier": 2,
        "parent_id": "32024R1689",
        "source_format": "html",
        "source_file": "32026R1755.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32026R1755",
        "license": "Public domain",
        "description": "Detailed arrangements for Commission proceedings under the AI Act.",
    },

    # ────── Tier 3: Sectoral (defer; per-vertical customers) ──────
    {
        "id": "32022R2554",
        "category": "eu_law",
        "name": "DORA",
        "version": "Reg. (EU) 2022/2554",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32022R2554.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2554",
        "license": "Public domain",
        "description": "Digital Operational Resilience Act — financial services software.",
    },
    {
        "id": "32017R0745",
        "category": "eu_law",
        "name": "Medical Device Regulation (MDR)",
        "version": "Reg. (EU) 2017/745",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32017R0745.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32017R0745",
        "license": "Public domain",
        "description": "Medical Device Regulation — software as medical device (SaMD).",
    },
    {
        "id": "32023R1230",
        "category": "eu_law",
        "name": "Machinery Regulation",
        "version": "Reg. (EU) 2023/1230",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32023R1230.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32023R1230",
        "license": "Public domain",
        "description": "Machinery products including AI safety components.",
    },
    {
        "id": "32002L0058",
        "category": "eu_law",
        "name": "ePrivacy Directive",
        "version": "Dir. 2002/58/EC",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32002L0058.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32002L0058",
        "license": "Public domain",
        "description": "Electronic communications confidentiality, cookies, direct marketing.",
    },
    {
        "id": "32024R1183",
        "category": "eu_law",
        "name": "eIDAS 2.0",
        "version": "Reg. (EU) 2024/1183",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32024R1183.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024R1183",
        "license": "Public domain",
        "description": "Digital identity, trust services, electronic signatures.",
    },
    {
        "id": "32025R0327",
        "category": "eu_law",
        "name": "European Health Data Space (EHDS)",
        "version": "Reg. (EU) 2025/327",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32025R0327.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32025R0327",
        "license": "Public domain",
        "description": "Health data sharing and secondary use.",
    },
    {
        "id": "32024L1640",
        "category": "eu_law",
        "name": "AMLD 6",
        "version": "Dir. (EU) 2024/1640",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32024L1640.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024L1640",
        "license": "Public domain",
        "description": "Anti-Money Laundering Directive.",
    },
    {
        "id": "32022R0868",
        "category": "eu_law",
        "name": "Data Governance Act",
        "version": "Reg. (EU) 2022/868",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32022R0868.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R0868",
        "license": "Public domain",
        "description": "Data intermediation services, altruistic data sharing.",
    },
    {
        "id": "32022R2065",
        "category": "eu_law",
        "name": "Digital Services Act (DSA)",
        "version": "Reg. (EU) 2022/2065",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32022R2065.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R2065",
        "license": "Public domain",
        "description": "Online platform obligations — recommender transparency, etc.",
    },
    {
        "id": "32022R1925",
        "category": "eu_law",
        "name": "Digital Markets Act (DMA)",
        "version": "Reg. (EU) 2022/1925",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32022R1925.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022R1925",
        "license": "Public domain",
        "description": "Gatekeeper obligations — self-preferencing, app store rules.",
    },
    {
        "id": "32022L2557",
        "category": "eu_law",
        "name": "CER Directive",
        "version": "Dir. (EU) 2022/2557",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32022L2557.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32022L2557",
        "license": "Public domain",
        "description": "Critical Entities Resilience Directive.",
    },
    {
        "id": "32019R0881",
        "category": "eu_law",
        "name": "Cybersecurity Act",
        "version": "Reg. (EU) 2019/881",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32019R0881.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32019R0881",
        "license": "Public domain",
        "description": "ENISA mandate + EU cybersecurity certification framework.",
    },
    {
        "id": "32025R0038",
        "category": "eu_law",
        "name": "Cyber Solidarity Act",
        "version": "Reg. (EU) 2025/38",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32025R0038.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32025R0038",
        "license": "Public domain",
        "description": "Cybersecurity incident response, cross-border SOCs.",
    },
    {
        "id": "32019L1937",
        "category": "eu_law",
        "name": "Whistleblower Directive",
        "version": "Dir. (EU) 2019/1937",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32019L1937.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32019L1937",
        "license": "Public domain",
        "description": "Whistleblower protection directive.",
    },
    {
        "id": "32023D1795",
        "category": "eu_law",
        "name": "EU-US Data Privacy Framework",
        "version": "Dec. (EU) 2023/1795",
        "issuing_body": "European Commission",
        "tier": 3,
        "source_format": "html",
        "source_file": "32023D1795.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32023D1795",
        "license": "Public domain",
        "description": "EU-US data transfer adequacy decision.",
    },
    {
        "id": "32016L0943",
        "category": "eu_law",
        "name": "Trade Secrets Directive",
        "version": "Dir. (EU) 2016/943",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32016L0943.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016L0943",
        "license": "Public domain",
        "description": "Trade secrets protection, source code protection.",
    },
    {
        "id": "32016L0680",
        "category": "eu_law",
        "name": "Law Enforcement Directive (LED)",
        "version": "Dir. (EU) 2016/680",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32016L0680.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016L0680",
        "license": "Public domain",
        "description": "Data protection in criminal-justice software.",
    },
    {
        "id": "32018R1807",
        "category": "eu_law",
        "name": "Free Flow of Non-Personal Data",
        "version": "Reg. (EU) 2018/1807",
        "issuing_body": "European Parliament and Council",
        "tier": 3,
        "source_format": "html",
        "source_file": "32018R1807.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32018R1807",
        "license": "Public domain",
        "description": "Removes data localisation requirements.",
    },
    {
        "id": "12012P000",
        "category": "eu_law",
        "name": "Charter of Fundamental Rights",
        "version": "Proclaimed 2012-10-26",
        "issuing_body": "European Parliament, Council, Commission",
        "tier": 4,
        "source_format": "html",
        "source_file": "12012P000.html",
        "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:12012P000",
        "license": "Public domain",
        "description": "Foundational rights document — interpretive only, not compliance basis.",
    },

    # ────── Comp AI frameworks (free sources) ──────
    {
        "id": "soc2",
        "category": "industry_standard",
        "name": "SOC 2 Trust Services Criteria",
        "version": "2017 with 2022 PoF revisions",
        "issuing_body": "AICPA",
        "tier": 2,
        "source_format": "json",
        "source_file": "SOC2-TSC.json",
        "source_url": "https://github.com/AIRiskGuy/aicpa-soc-tsc-json",
        "license": "GPL-3.0 (paraphrased from AICPA TSC)",
        "description": "Trust Services Criteria for SOC 2 audits. CC, A, C, PI, P categories.",
    },
    {
        "id": "iso27001",
        "category": "iso_standard",
        "name": "ISO/IEC 27001:2022 — Annex A Controls",
        "version": "2022",
        "issuing_body": "ISO/IEC",
        "tier": 2,
        "source_format": "json",
        "source_file": "ISO27001-AnnexA.json",
        "source_url": "https://github.com/sahilsinghi/iso27001-compliance-tracker",
        "license": "Paraphrased from ISO 27002:2022 guidance",
        "description": "Information security management. 93 Annex A controls across 4 themes.",
    },
    {
        "id": "iso42001",
        "category": "iso_standard",
        "name": "ISO/IEC 42001:2023 — Annex A Controls",
        "version": "2023",
        "issuing_body": "ISO/IEC",
        "tier": 2,
        "source_format": "markdown",
        "source_file": "ISO42001/references/iso42001-controls-annex-a.md",
        "source_url": "https://github.com/Sushegaad/Claude-Skills-Governance-Risk-and-Compliance",
        "license": "MIT (paraphrased from ISO 42001:2023)",
        "description": "AI Management System standard. 38 Annex A controls across 9 domains.",
    },
    {
        "id": "pci-dss",
        "category": "industry_standard",
        "name": "PCI DSS v4.0.1",
        "version": "4.0.1",
        "issuing_body": "PCI SSC",
        "tier": 2,
        "source_format": "yaml",
        "source_file": "PCI-DSS-v4.yml",
        "source_url": "https://github.com/ComplianceAsCode/content/blob/master/controls/pcidss_4.yml",
        "license": "Paraphrased from PCI DSS v4.0.1",
        "description": "Payment Card Industry Data Security Standard. 12 main requirements, 200+ sub-requirements.",
    },
    {
        "id": "iso9001",
        "category": "iso_standard",
        "name": "ISO 9001:2015 — Quality Management",
        "version": "2015",
        "issuing_body": "ISO",
        "tier": 3,
        "source_format": "html",
        "source_file": "ISO9001-Wikipedia.html",
        "source_url": "https://en.wikipedia.org/wiki/ISO_9001",
        "license": "CC-BY-SA (Wikipedia)",
        "description": "Quality Management Systems. 7 quality management principles. Full text is paywalled.",
    },
    {
        "id": "nen7510",
        "category": "regional_standard",
        "name": "NEN 7510:2017 — Information security in healthcare",
        "version": "2017",
        "issuing_body": "NEN (Netherlands)",
        "tier": 3,
        "source_format": "json",
        "source_file": "NEN7510.json",
        "source_url": "https://github.com/mazjo0100/dutch-standards-mcp",
        "license": "Extracted reference data",
        "description": "Dutch healthcare information security. 113 controls based on ISO 27001/27002 with healthcare additions.",
    },
    {
        "id": "hipaa-privacy",
        "category": "us_law",
        "name": "HIPAA Privacy Rule",
        "version": "45 CFR Part 164 Subpart E",
        "issuing_body": "U.S. HHS",
        "tier": 2,
        "source_format": "xml",
        "source_file": "HIPAA-Privacy-Rule.xml",
        "source_url": "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E",
        "license": "Public domain (US federal regulation)",
        "description": "Standards for privacy of individually identifiable health information.",
    },
    {
        "id": "hipaa-security",
        "category": "us_law",
        "name": "HIPAA Security Rule",
        "version": "45 CFR Part 164 Subpart C",
        "issuing_body": "U.S. HHS",
        "tier": 2,
        "source_format": "xml",
        "source_file": "HIPAA-Security-Rule.xml",
        "source_url": "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-C",
        "license": "Public domain",
        "description": "Security standards for electronic protected health information.",
    },
    {
        "id": "hipaa-general",
        "category": "us_law",
        "name": "HIPAA General Provisions",
        "version": "45 CFR Part 160",
        "issuing_body": "U.S. HHS",
        "tier": 2,
        "source_format": "xml",
        "source_file": "HIPAA-General-Provisions.xml",
        "source_url": "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-160",
        "license": "Public domain",
        "description": "General administrative requirements (definitions, complaints, enforcement).",
    },
    {
        "id": "ccpa",
        "category": "us_state_law",
        "name": "CCPA / CPRA",
        "version": "Cal. Civ. Code §1798.100 et seq.",
        "issuing_body": "California State Legislature",
        "tier": 3,
        "source_format": "html",
        "source_file": "CCPA.html",
        "source_url": "https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CIV&division=3.&part=4.&title=1.81.5",
        "license": "Public domain",
        "description": "California Consumer Privacy Act / California Privacy Rights Act.",
    },
    {
        "id": "nist-csf",
        "category": "global_standard",
        "name": "NIST Cybersecurity Framework 2.0",
        "version": "2.0",
        "issuing_body": "NIST",
        "tier": 2,
        "source_format": "pdf",
        "source_file": "NIST-CSF-v2.pdf",
        "source_url": "https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf",
        "license": "Public domain (NIST publication)",
        "description": "Cybersecurity Framework — Govern, Identify, Protect, Detect, Respond, Recover functions.",
    },
]


def by_id(framework_id: str) -> dict | None:
    for entry in FRAMEWORK_CATALOG:
        if entry["id"] == framework_id:
            return entry
    return None


def by_tier(tier: int) -> list[dict]:
    return [e for e in FRAMEWORK_CATALOG if e.get("tier") == tier]


def by_category(category: str) -> list[dict]:
    return [e for e in FRAMEWORK_CATALOG if e.get("category") == category]


if __name__ == "__main__":
    print(f"Total frameworks: {len(FRAMEWORK_CATALOG)}")
    print(f"\nBy tier:")
    for t in [1, 2, 3, 4]:
        items = by_tier(t)
        print(f"  Tier {t}: {len(items)} frameworks")
        for item in items:
            print(f"    - {item['id']:18s}  {item['name'][:60]}")
    print(f"\nBy category:")
    from collections import Counter
    cats = Counter(e["category"] for e in FRAMEWORK_CATALOG)
    for cat, count in cats.most_common():
        print(f"  {cat:25s}  {count}")
