"""Classify framework items + law articles by detection method via local Ollama.

Each item gets one of: 'code' | 'api' | 'hybrid' | 'process'
With a confidence score (0.0-1.0) and reasoning.

Usage:
    python3 scripts/classify_detection_methods.py --test      # small batch
    python3 scripts/classify_detection_methods.py --validate  # 50-item accuracy test
    python3 scripts/classify_detection_methods.py --full      # all items
    python3 scripts/classify_detection_methods.py --limit 100 # first 100
    python3 scripts/classify_detection_methods.py --dry-run   # don't write to DB
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

import requests  # noqa: E402
from sqlalchemy import select  # noqa: E402

from compliance.db import init_db, session_scope  # noqa: E402
from compliance.models import (  # noqa: E402
    Framework, FrameworkItem, Law, LawArticle, ReviewAction,
)

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger("classify_detection")

OLLAMA_URL = "http://localhost:11434/api/generate"
DEFAULT_MODEL = "gemma3:12b"

PROMPT_TEMPLATE = """You are classifying EU AI compliance obligations by their detection method — how compliance can be VERIFIED in practice.

## Detection methods

- "code":    Verifiable by reading source code alone. No external system needed.
             Examples: must display a notice; must have a human override button; must expose a deletion endpoint.
- "api":     Verifiable by querying an external integration alone. The source code is irrelevant.
             Examples: MFA enabled on AWS IAM; encryption-at-rest on S3; SBOM generated by Dependabot.
- "hybrid":  STRICT REQUIREMENT: verification fails if EITHER code OR API evidence is missing.
             Both code evidence (the function/feature exists in source) AND API evidence (it is actively being used/configured) must be present.
             Use "hybrid" ONLY when neither alone is sufficient — when you genuinely cannot tell if the requirement is met without checking both.
- "process": Cannot be auto-detected at all. Requires human attestation of a document, governance step, or organisational practice.
             Examples: risk assessment docs, board approval, training records, internal policies.

## Critical rule for "hybrid"

The LEAST-INCLUSIVE interpretation wins. Ask:
1. Can I verify this purely by reading source? → code
2. Can I verify this purely by querying an external system? → api
3. Is there any way to verify without code? → not hybrid (probably code or api)
4. Is there any way to verify without an external system? → not hybrid (probably code or process)
5. Is verification TRULY impossible without BOTH? → hybrid

Default to code/api/process when in doubt. "Hybrid" is the narrowest, most specific category.

## Examples

| Requirement | Method | Why |
|---|---|---|
| "Providers shall inform natural persons that they are interacting with an AI system" (AI Act Art. 50) | code | Source must render a notice — no API needed |
| "The provider shall implement a risk management system" (AI Act Art. 9) | process | Documented QMS — neither code nor API verifies it |
| "Personal data shall be encrypted at rest" (GDPR Art. 32) | api | Verified by querying infra (AWS KMS) — source code is irrelevant |
| "Multi-factor authentication shall be enabled" | api | Verified via Okta/AWS IAM |
| "Human oversight shall be effective" (AI Act Art. 14) | hybrid | Without the code gate, oversight can't exist; without the audit log API, you can't tell if it's actually used |
| "The organisation shall conduct annual risk assessments" | process | Documented risk register |
| "Logs shall be kept for 6 months" | hybrid | Code generates logs, but only storage API proves retention |
| "A vulnerability disclosure policy shall be published" (CRA) | process | Public document — neither code nor API verifies |
| "The system shall allow data subjects to request deletion" (GDPR Art. 17) | code | Source exposes an endpoint |
| "Threat intelligence shall be collected and used" (ISO A.5.7) | process | What matters is the documented intelligence process; tools don't verify it |
| "Configuration management shall be implemented" (ISO A.8.9) | process | Documented config mgmt process; tools support but don't verify it |
| "Cryptography shall be used to protect information" (ISO A.8.24) | api | Verified by querying what's actually encrypted (storage config) |
| "Secure coding standards shall be established" (ISO A.8.28) | process | Standards are documented; tools (linters) only flag violations, not prove compliance |
| "Change management shall be controlled" (ISO A.8.32) | process | The process is documented; tools help but don't verify |
| "AI system requirements shall be documented" (ISO A.6.2.2) | process | Documentation requirement |
| "Network security controls shall be configured" (PCI 1.1) | hybrid | Config in code/IaC, but compliance needs runtime verification |

## Output format

Respond with ONLY this JSON (no prose):
{{"method": "code|api|hybrid|process", "confidence": 0.0-1.0, "reasoning": "<one sentence>"}}

## Requirement to classify

Framework: {framework_name} ({framework_id})
Code: {code}
Title: {title}

Text:
\"\"\"
{content}
\"\"\"

JSON:
"""


def call_ollama(prompt: str, model: str = DEFAULT_MODEL, timeout: int = 60) -> dict:
    """Call local Ollama with structured JSON output."""
    try:
        r = requests.post(
            OLLAMA_URL,
            json={
                "model": model,
                "prompt": prompt,
                "format": "json",
                "stream": False,
                "options": {"temperature": 0.1},  # low temp for consistency
            },
            timeout=timeout,
        )
        r.raise_for_status()
        return json.loads(r.json()["response"])
    except Exception as e:
        return {"method": "process", "confidence": 0.0, "reasoning": f"OLLAMA ERROR: {e}"}


def classify_item(
    framework_id: str,
    framework_name: str,
    code: str,
    title: str,
    content: str,
    model: str = DEFAULT_MODEL,
    max_chars: int = 1500,
) -> dict:
    """Classify a single item via Ollama."""
    if len(content) > max_chars:
        content = content[:max_chars] + "…"
    prompt = PROMPT_TEMPLATE.format(
        framework_name=framework_name,
        framework_id=framework_id,
        code=code,
        title=title or "(no title)",
        content=content or "(no content)",
    )
    return call_ollama(prompt, model=model)


# ─────────────────────────────────────────────────────────────────────
# Test batch selection — diverse items across frameworks
# ─────────────────────────────────────────────────────────────────────

TEST_BATCH = [
    # (source, framework_id, code) — EU laws use law_articles
    # AI Act — mix of code/process/hybrid
    ("law", "32024R1689", "5"),       # Art. 5 — prohibited AI (process)
    ("law", "32024R1689", "14"),      # Art. 14 — human oversight (hybrid)
    ("law", "32024R1689", "50"),      # Art. 50 — transparency (code)
    ("law", "32024R1689", "9"),       # Art. 9 — risk management (process)
    ("law", "32024R1689", "10"),      # Art. 10 — data governance (hybrid)
    # GDPR — mix
    ("law", "32016R0679", "32"),      # Art. 32 — security (api)
    ("law", "32016R0679", "25"),      # Art. 25 — privacy by design (code)
    ("law", "32016R0679", "35"),      # Art. 35 — DPIA (process)
    ("law", "32016R0679", "17"),      # Art. 17 — right to erasure (code)
    # CRA — mostly technical
    ("law", "32024R2847", "12"),      # Art. 12 — vulnerability handling (hybrid)
    ("law", "32024R2847", "13"),      # Art. 13 — separate reporting (process)
    # SOC 2 — mix
    ("framework", "soc2", "CC6.1"),   # Logical access (api)
    ("framework", "soc2", "CC1.4"),   # Risk assessment (process)
    ("framework", "soc2", "CC8.1"),   # Change management (hybrid)
    ("framework", "soc2", "P6.1"),    # Logical access — production (api)
    # ISO 27001 — mix
    ("framework", "iso27001", "A.5.1"),   # Policies (process)
    ("framework", "iso27001", "A.8.5"),   # Secure authentication (api)
    ("framework", "iso27001", "A.8.28"),  # Secure coding (code)
    # ISO 42001 — AI-specific
    ("framework", "iso42001", "A.2.2"),   # AI policy (process)
    ("framework", "iso42001", "A.6.2.2"), # AI risk assessment (process)
    ("framework", "iso42001", "A.8.5"),   # Communication plan (process)
    # HIPAA — mix (codes are "45 CFR 164.XXX" format)
    ("framework", "hipaa-security", "45 CFR 164.312"),  # Technical safeguards (api)
    ("framework", "hipaa-security", "45 CFR 164.308"),  # Admin safeguards (process)
    ("framework", "hipaa-privacy", "45 CFR 164.524"),   # Right of access (code)
    # PCI DSS — technical
    ("framework", "pci-dss", "1.1"),     # Network security controls (hybrid)
    ("framework", "pci-dss", "3.5"),     # Cryptographic protection (api)
    ("framework", "pci-dss", "10.2"),    # Audit logs (hybrid)
]


# ─────────────────────────────────────────────────────────────────────
# Validation batch — 50 items where expected classification is unambiguous
# Format: (source, framework_id, code, expected_method, note)
# ─────────────────────────────────────────────────────────────────────

VALIDATION_BATCH = [
    # ────── EU LAWS (20 items) ──────
    # AI Act
    ("law", "32024R1689", "1",        "process", "Subject matter — meta article"),
    ("law", "32024R1689", "5",        "process", "Prohibited AI practices (mostly governance)"),
    ("law", "32024R1689", "9",        "process", "Risk management system (documented)"),
    ("law", "32024R1689", "10",       "process", "Data governance (data + docs)"),
    ("law", "32024R1689", "14",       "hybrid",  "Human oversight (code gate + API events)"),
    ("law", "32024R1689", "50",       "code",    "Transparency — user-facing notice"),
    ("law", "32024R1689", "113",      "process", "Entry into force — procedural"),

    # GDPR
    ("law", "32016R0679", "1",        "process", "Subject matter — meta"),
    ("law", "32016R0679", "4",        "process", "Definitions only"),
    ("law", "32016R0679", "6",        "process", "Lawfulness (legal/organizational)"),
    ("law", "32016R0679", "17",       "code",    "Right to erasure — needs endpoint"),
    ("law", "32016R0679", "25",       "code",    "Privacy by design (in source)"),
    ("law", "32016R0679", "32",       "api",     "Security of processing — verified via infra config"),
    ("law", "32016R0679", "35",       "process", "DPIA — documented assessment"),
    ("law", "32016R0679", "99",       "process", "Entry into force — procedural"),

    # CRA
    ("law", "32024R2847", "1",        "process", "Subject matter"),
    ("law", "32024R2847", "5",        "process", "General principles (governance)"),
    ("law", "32024R2847", "12",       "process", "Vulnerability handling — documented process"),
    ("law", "32024R2847", "13",       "process", "Reporting obligations — documentation"),
    ("law", "32024R2847", "14",       "process", "Conformity assessment — procedure"),

    # ────── SOC 2 (8 items) ──────
    ("framework", "soc2", "CC1.4",    "process", "Risk assessment"),
    ("framework", "soc2", "CC6.1",    "hybrid",  "Logical access — code defines, API verifies"),
    ("framework", "soc2", "CC6.6",    "hybrid",  "External access — code + API"),
    ("framework", "soc2", "CC7.2",    "hybrid",  "System monitoring — code + SIEM API"),
    ("framework", "soc2", "CC8.1",    "process", "Change management — documented process"),
    ("framework", "soc2", "P6.1",     "code",    "Consent for disclosure — in source"),
    ("framework", "soc2", "P7.1",     "process", "Quality of personal info — org practice"),
    ("framework", "soc2", "A1.1",     "process", "Availability — capacity/monitoring docs"),

    # ────── ISO 27001 (8 items) ──────
    ("framework", "iso27001", "A.5.1",   "process", "Policies for information security"),
    ("framework", "iso27001", "A.5.7",   "process", "Threat intelligence — documented"),
    ("framework", "iso27001", "A.8.5",   "hybrid",  "Secure authentication — code + IdP API"),
    ("framework", "iso27001", "A.8.9",   "hybrid",  "Configuration management — IaC code + monitoring API"),
    ("framework", "iso27001", "A.8.24",  "api",     "Cryptography — verified via storage config"),
    ("framework", "iso27001", "A.8.28",  "process", "Secure coding standards — documented"),
    ("framework", "iso27001", "A.8.32",  "process", "Change management — documented"),
    ("framework", "iso27001", "A.8.34",  "hybrid",  "Protection during audit testing"),

    # ────── ISO 42001 (6 items) ──────
    ("framework", "iso42001", "A.2.2",   "process", "AI policy"),
    ("framework", "iso42001", "A.6.2.2", "process", "AI requirements documented"),
    ("framework", "iso42001", "A.6.2.5", "process", "AI risk treatment — documented"),
    ("framework", "iso42001", "A.8.4",   "process", "AI objectives — planning"),
    ("framework", "iso42001", "A.8.5",   "process", "Communication plan"),
    ("framework", "iso42001", "A.9.2",   "process", "AI system lifecycle — documented"),

    # ────── HIPAA (5 items) ──────
    ("framework", "hipaa-security", "45 CFR 164.308", "process", "Admin safeguards — documented"),
    ("framework", "hipaa-security", "45 CFR 164.310", "process", "Physical safeguards"),
    ("framework", "hipaa-security", "45 CFR 164.312", "hybrid",  "Technical safeguards (auth + audit)"),
    ("framework", "hipaa-privacy",  "45 CFR 164.524", "code",    "Right of access — needs endpoint"),
    ("framework", "hipaa-privacy",  "45 CFR 164.530", "process", "Workforce training — documented"),

    # ────── PCI DSS (3 items) ──────
    ("framework", "pci-dss", "1.1",     "hybrid",  "NSC processes — config + documented"),
    ("framework", "pci-dss", "3.5",     "api",     "PAN protection — verified via storage"),
    ("framework", "pci-dss", "10.2",    "hybrid",  "Audit logs (generated + stored)"),
]


def fetch_items(session, batch: list[tuple]) -> list[dict]:
    """Resolve batch tuples into items with their content.

    Accepts both 3-tuple (source, fw_id, code) and 5-tuple
    (source, fw_id, code, expected_method, note) — for validation mode.
    """
    items = []
    for entry in batch:
        # Unpack with optional expected_method + note (5-tuple)
        if len(entry) == 5:
            source, fw_id, code, expected_method, note = entry
        else:
            source, fw_id, code = entry
            expected_method = None
            note = None

        if source == "law":
            # Articles are stored with all sub-clauses flattened in one row,
            # so match by prefix (article_number LIKE '5%' matches '5', '5(a)(b)...', etc.)
            row = session.execute(
                select(LawArticle, Law)
                .join(Law, LawArticle.celex == Law.celex)
                .where(
                    LawArticle.celex == fw_id,
                    LawArticle.article_number.like(f"{code}%"),
                )
                .order_by(LawArticle.article_number)
            ).first()
            if not row:
                log.warning(f"  ⚠ Not found: law {fw_id} art. {code}")
                continue
            art, law = row
            items.append({
                "source": "law",
                "id": art.id,
                "framework_id": fw_id,
                "framework_name": law.short_name or law.long_name,
                "code": f"Article {art.article_number}",
                "title": art.title,
                "content": art.text,
                "expected_method": expected_method,
                "note": note,
            })
        else:  # framework
            row = session.execute(
                select(FrameworkItem, Framework)
                .join(Framework, FrameworkItem.framework_id == Framework.id)
                .where(FrameworkItem.framework_id == fw_id, FrameworkItem.code == code)
            ).first()
            if not row:
                log.warning(f"  ⚠ Not found: framework {fw_id} item {code}")
                continue
            item, fw = row
            items.append({
                "source": "framework",
                "id": item.id,
                "framework_id": fw_id,
                "framework_name": fw.name,
                "code": item.code,
                "title": item.title,
                "content": item.content,
                "expected_method": expected_method,
                "note": note,
            })
    return items


def write_to_db(session, item: dict, classification: dict, dry_run: bool = False) -> None:
    """Persist classification to DB."""
    if dry_run:
        return
    if item["source"] == "law":
        art = session.get(LawArticle, item["id"])
    else:
        art = session.get(FrameworkItem, item["id"])

    art.detection_method = classification["method"]
    art.detection_confidence = classification.get("confidence")
    art.detection_classified_by = "llm"
    art.detection_reasoning = classification.get("reasoning", "")[:1000]
    art.detection_reviewed_at = datetime.utcnow()


def run_full(
    model: str = DEFAULT_MODEL,
    batch_size: int = 50,
    min_content_chars: int = 50,
    limit: int | None = None,
) -> dict:
    """Classify ALL unclassified items in the database.

    - Skips items already classified (detection_classified_by IS NOT NULL)
    - Skips items with content shorter than min_content_chars
    - Commits every batch_size items for resumability
    - Logs progress to stderr
    """
    init_db()
    started = time.time()
    stats = {
        "law_articles": 0,
        "framework_items": 0,
        "skipped_short": 0,
        "already_done": 0,
        "method_counts": {},
        "avg_confidence": 0.0,
        "low_confidence": 0,
    }

    def process_batch(items: list[dict]) -> None:
        for item in items:
            classification = classify_item(
                framework_id=item["framework_id"],
                framework_name=item["framework_name"],
                code=item["code"],
                title=item["title"],
                content=item["content"],
                model=model,
            )
            method = classification.get("method", "process")
            conf = classification.get("confidence", 0.0)

            if item["source"] == "law":
                row = session.get(LawArticle, item["id"])
                stats["law_articles"] += 1
            else:
                row = session.get(FrameworkItem, item["id"])
                stats["framework_items"] += 1

            row.detection_method = method
            row.detection_confidence = conf
            row.detection_classified_by = "llm"
            row.detection_reasoning = classification.get("reasoning", "")[:1000]
            row.detection_reviewed_at = datetime.utcnow()

            stats["method_counts"][method] = stats["method_counts"].get(method, 0) + 1
            if conf < 0.7:
                stats["low_confidence"] += 1

        # Commit this batch
        session.commit()

    with session_scope() as session:
        # Fetch all law_articles that need classification
        law_rows = session.execute(
            select(LawArticle, Law)
            .join(Law, LawArticle.celex == Law.celex)
            .where(
                LawArticle.detection_classified_by.is_(None),
                LawArticle.text.isnot(None),
            )
            .order_by(LawArticle.celex, LawArticle.id)
        ).all()

        # Fetch all framework_items that need classification
        fw_rows = session.execute(
            select(FrameworkItem, Framework)
            .join(Framework, FrameworkItem.framework_id == Framework.id)
            .where(
                FrameworkItem.detection_classified_by.is_(None),
                FrameworkItem.content.isnot(None),
            )
            .order_by(FrameworkItem.framework_id, FrameworkItem.id)
        ).all()

        # Convert to unified item dicts
        all_items: list[dict] = []
        for art, law in law_rows:
            if not art.text or len(art.text) < min_content_chars:
                stats["skipped_short"] += 1
                continue
            all_items.append({
                "source": "law",
                "id": art.id,
                "framework_id": law.celex,
                "framework_name": law.short_name or law.long_name,
                "code": f"Article {art.article_number}",
                "title": art.title,
                "content": art.text,
            })

        for item, fw in fw_rows:
            if not item.content or len(item.content) < min_content_chars:
                stats["skipped_short"] += 1
                continue
            all_items.append({
                "source": "framework",
                "id": item.id,
                "framework_id": fw.id,
                "framework_name": fw.name,
                "code": item.code,
                "title": item.title,
                "content": item.content,
            })

        if limit:
            all_items = all_items[:limit]

        total = len(all_items)
        log.info(f"Classifying {total} items ({stats['skipped_short']} skipped for short content)")
        log.info(f"  Law articles: {stats['law_articles']} to do")
        log.info(f"  Framework items: {stats['framework_items']} to do")
        log.info(f"  Model: {model}")
        log.info(f"  Batch size: {batch_size}\n")

        # Process in batches with progress logging
        for batch_start in range(0, total, batch_size):
            batch_end = min(batch_start + batch_size, total)
            batch = all_items[batch_start:batch_end]

            t0 = time.time()
            process_batch(batch)
            elapsed = time.time() - t0
            per_item = elapsed / len(batch) if batch else 0
            eta_total_sec = per_item * (total - batch_end)
            eta_min = eta_total_sec / 60

            log.info(
                f"  [{batch_end:4d}/{total}] "
                f"batch={len(batch):3d} "
                f"elapsed={elapsed:5.1f}s "
                f"per_item={per_item:.2f}s "
                f"ETA={eta_min:.1f}min "
                f"methods={stats['method_counts']}"
            )

        # Log audit
        session.add(ReviewAction(
            celex="classification_full",
            action="full_classification",
            reason=(
                f"Classified {stats['law_articles']} law articles + "
                f"{stats['framework_items']} framework items with {model}"
            ),
            actor="classify_detection_methods",
        ))
        session.commit()

    total_done = stats["law_articles"] + stats["framework_items"]
    total_elapsed = time.time() - started
    log.info(f"\n=== Full classification complete ===")
    log.info(f"  Total classified: {total_done}")
    log.info(f"  Skipped (short content): {stats['skipped_short']}")
    log.info(f"  Total elapsed: {total_elapsed/60:.1f}min")
    log.info(f"  Method distribution: {stats['method_counts']}")

    return stats


def run_test_batch(model: str = DEFAULT_MODEL, dry_run: bool = False) -> dict:
    """Run classification on the test batch."""
    init_db()
    stats = {
        "results": [],
        "method_counts": {},
        "avg_confidence": 0.0,
        "low_confidence": [],
    }

    with session_scope() as session:
        items = fetch_items(session, TEST_BATCH)
        log.info(f"Loaded {len(items)}/{len(TEST_BATCH)} items from test batch\n")

        for i, item in enumerate(items, 1):
            t0 = time.time()
            classification = classify_item(
                framework_id=item["framework_id"],
                framework_name=item["framework_name"],
                code=item["code"],
                title=item["title"],
                content=item["content"],
                model=model,
            )
            elapsed = time.time() - t0

            result = {
                **item,
                "classification": classification,
                "elapsed_s": round(elapsed, 1),
            }
            stats["results"].append(result)

            method = classification.get("method", "unknown")
            conf = classification.get("confidence", 0)
            stats["method_counts"][method] = stats["method_counts"].get(method, 0) + 1

            if conf < 0.7:
                stats["low_confidence"].append(result)

            write_to_db(session, item, classification, dry_run=dry_run)

            # Inline progress
            conf_icon = "🟢" if conf >= 0.7 else "🟡" if conf >= 0.4 else "🔴"
            content_preview = (item["content"] or "")[:60].replace("\n", " ")
            log.info(
                f"  [{i:2d}/{len(items)}] {conf_icon} {method:7s} ({conf:.2f}) "
                f"{item['framework_id']:15s} {item['code']:15s} — "
                f"{content_preview}…"
            )

        # Log review action
        session.add(ReviewAction(
            celex="classification_test",
            action="test_classification",
            reason=f"Classified {len(items)} items with {model}",
            actor="classify_detection_methods",
        ))

    confidences = [r["classification"].get("confidence", 0) for r in stats["results"]]
    stats["avg_confidence"] = round(sum(confidences) / len(confidences), 3) if confidences else 0

    return stats


def run_validation(model: str = DEFAULT_MODEL, dry_run: bool = True) -> dict:
    """Run validation batch and compute accuracy against expected classifications."""
    init_db()
    stats = {
        "results": [],
        "correct": 0,
        "wrong": 0,
        "by_method": {},
        "confusion": {},  # (expected → actual) counts
        "errors": [],
    }

    with session_scope() as session:
        items = fetch_items(session, VALIDATION_BATCH)
        items = [i for i in items if i.get("expected_method")]  # skip not-found
        log.info(f"Loaded {len(items)}/{len(VALIDATION_BATCH)} items from validation batch\n")

        for i, item in enumerate(items, 1):
            t0 = time.time()
            classification = classify_item(
                framework_id=item["framework_id"],
                framework_name=item["framework_name"],
                code=item["code"],
                title=item["title"],
                content=item["content"],
                model=model,
            )
            elapsed = time.time() - t0

            actual = classification.get("method", "?")
            expected = item["expected_method"]
            correct = (actual == expected)

            result = {
                **item,
                "classification": classification,
                "actual": actual,
                "expected": expected,
                "correct": correct,
                "elapsed_s": round(elapsed, 1),
            }
            stats["results"].append(result)

            if correct:
                stats["correct"] += 1
            else:
                stats["wrong"] += 1
                confusion_key = f"{expected}→{actual}"
                stats["confusion"][confusion_key] = stats["confusion"].get(confusion_key, 0) + 1

            # Track per-method accuracy
            for m in (expected, actual):
                stats["by_method"].setdefault(m, {"correct": 0, "total": 0})
                stats["by_method"][m]["total"] += 1
            if correct:
                stats["by_method"][expected]["correct"] += 1

            icon = "✅" if correct else "❌"
            conf = classification.get("confidence", 0)
            log.info(
                f"  [{i:2d}/{len(items)}] {icon} {actual:7s} (expected {expected:7s}, conf={conf:.2f}) "
                f"{item['framework_id'][:18]:18s} {item['code'][:18]:18s}"
            )

        # Log review action
        session.add(ReviewAction(
            celex="validation",
            action="validation_run",
            reason=f"Validated {len(items)} items with {model}",
            actor="classify_detection_methods",
        ))

    stats["accuracy"] = round(stats["correct"] / len(items), 3) if items else 0
    return stats


def print_validation_report(stats: dict) -> None:
    """Print validation results with confusion matrix."""
    n = len(stats["results"])
    print("\n" + "=" * 100)
    print(f"VALIDATION RESULTS — {stats['correct']}/{n} correct ({stats['accuracy']*100:.1f}%)")
    print("=" * 100)

    # Per-method accuracy
    print("\nAccuracy by expected method:")
    print(f"  {'Method':10s} {'Correct':8s} {'Total':6s} {'Accuracy':10s}")
    for method in sorted(stats["by_method"]):
        m = stats["by_method"][method]
        acc = m["correct"] / m["total"] if m["total"] else 0
        print(f"  {method:10s} {m['correct']:8d} {m['total']:6d} {acc*100:6.1f}%")

    # Confusion matrix
    if stats["confusion"]:
        print("\nConfusion (expected → actual):")
        for k, v in sorted(stats["confusion"].items(), key=lambda x: -x[1]):
            print(f"  {k:25s}  {'█' * v}  {v}")

    # Disagreements
    print("\n" + "-" * 100)
    print(f"{'Actual':8s} {'Expected':9s} {'Framework':30s} {'Code':25s} Reasoning")
    print("-" * 100)
    for r in stats["results"]:
        if r["correct"]:
            continue
        actual = r["actual"]
        expected = r["expected"]
        reasoning = r["classification"].get("reasoning", "")[:80]
        print(
            f"{actual:8s} {expected:9s} "
            f"{r['framework_name'][:30]:30s} {r['code'][:25]:25s} {reasoning}"
        )

    # Verdict
    print("\n" + "=" * 100)
    if stats["accuracy"] >= 0.9:
        verdict = "✅ PASS — accuracy ≥90%, safe to scale to all items"
    elif stats["accuracy"] >= 0.8:
        verdict = "⚠️  MARGINAL — accuracy 80-90%, review disagreements before scaling"
    else:
        verdict = "❌ FAIL — accuracy <80%, prompt needs tuning"
    print(verdict)
    print("=" * 100)


def print_report(stats: dict) -> None:
    """Pretty-print classification results."""
    print("\n" + "=" * 100)
    print("CLASSIFICATION RESULTS")
    print("=" * 100)

    # Summary
    print(f"\nMethod distribution:")
    for method, count in sorted(stats["method_counts"].items()):
        print(f"  {method:8s}  {'█' * count} {count}")
    print(f"\nAverage confidence: {stats['avg_confidence']}")
    print(f"Low-confidence items (<0.7): {len(stats['low_confidence'])}")

    # Detailed table
    print("\n" + "-" * 100)
    print(f"{'Method':8s} {'Conf':5s} {'Framework':30s} {'Code':25s} Reasoning")
    print("-" * 100)
    for r in stats["results"]:
        method = r["classification"].get("method", "?")
        conf = r["classification"].get("confidence", 0)
        reasoning = r["classification"].get("reasoning", "")[:80]
        print(
            f"{method:8s} {conf:5.2f} "
            f"{r['framework_name'][:30]:30s} {r['code'][:25]:25s} {reasoning}"
        )

    # Low-confidence items
    if stats["low_confidence"]:
        print("\n" + "=" * 100)
        print("LOW CONFIDENCE — needs human review:")
        print("=" * 100)
        for r in stats["low_confidence"]:
            print(f"\n  {r['framework_name']} {r['code']}")
            print(f"  Content: {(r['content'] or '')[:200]}…")
            print(f"  LLM said: {r['classification']}")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--test", action="store_true", help="Run small test batch (default)")
    p.add_argument("--validate", action="store_true", help="Run 50-item validation against expected answers")
    p.add_argument("--batch-size", type=int, default=50, help="Commit batch size (default 50)")
    p.add_argument("--full", action="store_true", help="Classify all unclassified items")
    p.add_argument("--limit", type=int, help="Classify first N items")
    p.add_argument("--dry-run", action="store_true", help="Don't write to DB")
    p.add_argument("--model", default=DEFAULT_MODEL, help=f"Ollama model (default: {DEFAULT_MODEL})")
    args = p.parse_args()

    if args.full:
        stats = run_full(model=args.model, batch_size=args.batch_size, limit=args.limit)
        return

    if args.validate:
        stats = run_validation(model=args.model, dry_run=True)
        print_validation_report(stats)
        return

    stats = run_test_batch(model=args.model, dry_run=args.dry_run)
    print_report(stats)


if __name__ == "__main__":
    main()
