#!/usr/bin/env python3
"""Convert the single regulation note into an index.

`32024R1689 - EU AI Act.md` becomes the regulation-level index: it
lists all 113 article notes via Obsidian wiki links, but does NOT
duplicate the Runtime Testability content (which now lives in the
per-article notes under `EU AI Act/`).

Idempotent: re-running appends nothing new if the generated block is
already present; only the block between the index markers is replaced.
"""
from __future__ import annotations

import argparse
import os
import re
import sqlite3
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


INDEX_START = "<!-- ARTICLE_INDEX:START -->"
INDEX_END = "<!-- ARTICLE_INDEX:END -->"


def _bare_article_number(article_number: str) -> int:
    m = re.match(r"^(\d+)", article_number)
    return int(m.group(1)) if m else -1


def _filename_safe_title(title: str) -> str:
    t = (title or "").strip().replace("\n", " ").replace("\r", " ")
    t = re.sub(r"[`/\\:*?\"<>|]", "", t)
    t = t.strip(" .")
    return t or "Untitled"


def _load_articles(conn: sqlite3.Connection, celex: str) -> list[tuple[int, str]]:
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT article_number, title FROM law_articles WHERE celex = ? ORDER BY id",
        (celex,),
    ).fetchall()
    return [(_bare_article_number(r["article_number"]), r["title"]) for r in rows]


def _render_index_block(articles: list[tuple[int, str]], subdir: str) -> str:
    lines: list[str] = []
    lines.append(f"{INDEX_START}\n\n")
    lines.append(
        f"Per-article notes are materialised under `EU AI Act/`. "
        f"This index is generated by `sync_regulation_index.py`; "
        f"do not edit the rows below by hand — re-run the sync to refresh.\n\n"
    )
    lines.append("| Article | Title | Note |\n")
    lines.append("|---------|-------|------|\n")
    for bare, title in articles:
        safe = _filename_safe_title(title)
        # Obsidian wikilink syntax: [[subdir/file|display]]
        link = f"[[{subdir}/Article {bare} - {safe}|Article {bare} — {title or ''}]]"
        link = link.replace("\n", " ").replace("\r", " ")
        lines.append(f"| {bare} | {title or ''} | {link} |\n")
    lines.append(f"\n{INDEX_END}\n")
    return "".join(lines)


def _replace_or_append(text: str, start: str, end: str, new_block: str) -> str:
    s = text.find(start)
    if s == -1:
        sep = "" if text.endswith("\n") else "\n"
        return text + sep + "\n" + new_block
    e = text.find(end, s)
    if e == -1:
        sep = "" if text.endswith("\n") else "\n"
        return text + sep + "\n" + new_block
    e += len(end)
    return text[:s] + new_block + text[e:]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--celex", default="32024R1689")
    ap.add_argument(
        "--vault",
        default=os.environ.get(
            "OBSIDIAN_VAULT_PATH",
            "<set OBSIDIAN_VAULT_PATH to your local Obsidian vault>",
        ),
    )
    ap.add_argument(
        "--note-name",
        default=None,
        help="Override regulation note filename",
    )
    ap.add_argument(
        "--subdir",
        default="EU AI Act",
    )
    ap.add_argument(
        "--db",
        default=str(PROJECT_ROOT / "data" / "eu_ai_compliance.db"),
    )
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    db_path = Path(args.db)
    vault_root = Path(args.vault)
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        law = conn.execute(
            "SELECT short_name FROM laws WHERE celex = ?", (args.celex,)
        ).fetchone()
        if law is None:
            print(f"law not found: {args.celex}", file=sys.stderr)
            return 1
        articles = _load_articles(conn, args.celex)
    finally:
        conn.close()

    note_name = args.note_name or f"{args.celex} - {law['short_name']}.md"
    note_path = vault_root / note_name
    if not note_path.exists():
        print(f"regulation note not found: {note_path}", file=sys.stderr)
        return 1

    block = _render_index_block(articles, args.subdir)
    if args.dry_run:
        print(f"[dry-run] would update {note_path}")
        return 0
    existing = note_path.read_text(encoding="utf-8")
    updated = _replace_or_append(existing, INDEX_START, INDEX_END, block)
    note_path.write_text(updated, encoding="utf-8")
    print(f"updated {note_path} with {len(articles)} article links")
    return 0


if __name__ == "__main__":
    sys.exit(main())
